name: Update Upstream Branch

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  rebase-to-upstream:
    runs-on: ubuntu-latest

    concurrency:
      group: update-upstream
      cancel-in-progress: true

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git user
        run: |
          git config user.name  "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch latest main
        run: git fetch origin main

      - name: Switch to upstream
        run: git checkout upstream

      - name: Rebase upstream onto main
        run: git rebase origin/main

      - name: Push upstream branch
        run: git push origin upstream --force-with-lease
